# Generated by Django 4.2.4 on 2023-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
