# Generated by Django 4.2.4 on 2023-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(),
        ),
    ]
