# Generated by Django 4.2.4 on 2023-09-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
